feat: security improvements

diff --git a/usr/local/bin/servonaut-setup b/usr/local/bin/servonaut-setup
--- a/usr/local/bin/servonaut-setup
+++ b/usr/local/bin/servonaut-setup
@@ -58,12 +58,24 @@ fi
 
 echo -e "\n🛡️  Hardening the server...\n"
 sleep 1
+setup_system_security || {
+    echo -e "\n❌ Failed to configure system security. Exiting."
+    exit 1
+}
+setup_ssh_security || {
+    echo -e "\n❌ Failed to harden SSH. Exiting."
+    exit 1
+}
 setup_automatic_security_updates || {
     echo -e "\n❌ Failed to set up automatic security updates. Exiting."
     exit 1
 }
 setup_fail2ban || {
     echo -e "\n❌ Failed to set up fail2ban. Exiting."
+    exit 1
+}
+setup_crowdsec || {
+    echo -e "\n❌ Failed to set up CrowdSec. Exiting."
     exit 1
 }
 setup_ufw || {
