feat: move security stuff before setting up nuxt

diff --git a/usr/local/bin/servonaut-setup b/usr/local/bin/servonaut-setup
--- a/usr/local/bin/servonaut-setup
+++ b/usr/local/bin/servonaut-setup
@@ -55,6 +55,21 @@ if [ "$db_choice" = "PostgreSQL" ]; then
     }
 fi
 
+echo -e "\n🛡️  Hardening the server...\n"
+sleep 1
+setup_automatic_security_updates || {
+    echo -e "\n❌ Failed to set up automatic security updates. Exiting."
+    exit 1
+}
+setup_fail2ban || {
+    echo -e "\n❌ Failed to set up fail2ban. Exiting."
+    exit 1
+}
+setup_ufw || {
+    echo -e "\n❌ Failed to set up UFW. Exiting."
+    exit 1
+}
+
 echo -e "\n🛠️  Setting up Nuxt project...\n"
 sleep 1
 setup_nuxt || {
@@ -81,21 +96,6 @@ sleep 1
 systemctl daemon-reload
 systemctl restart nuxt.service || {
     echo -e "\n❌ Failed to restart Nuxt service. Exiting."
-    exit 1
-}
-
-echo -e "\n🛡️  Hardening the server...\n"
-sleep 1
-setup_automatic_security_updates || {
-    echo -e "\n❌ Failed to set up automatic security updates. Exiting."
-    exit 1
-}
-setup_fail2ban || {
-    echo -e "\n❌ Failed to set up fail2ban. Exiting."
-    exit 1
-}
-setup_ufw || {
-    echo -e "\n❌ Failed to set up UFW. Exiting."
     exit 1
 }
 
